# Generated by Django 2.1.5 on 2019-01-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='cell_extraction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.CellExtraction'),
        ),
    ]
