# Generated by Django 2.1.5 on 2019-01-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190119_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='cell_extraction_id',
            new_name='cell_extraction',
        ),
    ]
