# Generated by Django 2.1.5 on 2019-01-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190119_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.Patient'),
            preserve_default=False,
        ),
    ]
