# Generated by Django 2.1.5 on 2019-01-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slide_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='cell_category_id',
            new_name='cell_category',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='slide_id',
            new_name='slide',
        ),
    ]
