# Generated by Django 2.1.6 on 2019-02-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cellextraction_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellextraction',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cell_extractions', to='api.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cellextraction',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_extractions', to='api.Doctor'),
        ),
    ]
