# Generated by Django 2.2 on 2019-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_anamnesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='allergy',
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='acufeni',
            field=models.CharField(choices=[('SX', 'sinistra'), ('DX', 'destra'), ('EX', 'bilaterale')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='allergy_fra',
            field=models.CharField(choices=[('AL', 'alimenti'), ('IN', 'inalanti')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='allergy_gen',
            field=models.CharField(choices=[('AL', 'alimenti'), ('IN', 'inalanti')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='asma_bronch_fra',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='asma_bronch_gen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='bruciore_cong',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='febbre',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='fotofobia',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='ipoacusia',
            field=models.CharField(choices=[('SX', 'sinistra'), ('DX', 'destra'), ('EX', 'bilaterale')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='lacrimazione',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='ostr_nas',
            field=models.CharField(choices=[('SX', 'sinistra'), ('DX', 'destra'), ('EX', 'bilaterale')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='ovatt_aur',
            field=models.CharField(choices=[('SX', 'sinistra'), ('DX', 'destra'), ('EX', 'bilaterale')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='pir_nas',
            field=models.CharField(choices=[('NFM', 'normoformata'), ('GIB', 'gibbo'), ('SCO', 'scoiosi'), ('DEF', 'deformazioni varie')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='polip_nas_fra',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='polip_nas_gen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='prob_olf',
            field=models.CharField(choices=[('IP', 'iposmia'), ('AN', 'anosmia'), ('CA', 'cacosimia')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='prur_nas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='prurito_cong',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='rinorrea',
            field=models.CharField(choices=[('SI', 'sierosa'), ('MU', 'mucosa'), ('PU', 'purulenta'), ('EM', 'ematica')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='setto_nas',
            field=models.CharField(choices=[('ASS', 'in asse'), ('DVS', 'deviato a sinistra'), ('DVD', 'deviato a destra'), ('ESI', 'esse italica')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='sindr_ver',
            field=models.CharField(choices=[('SO', 'soggettiva'), ('OG', 'oggettiva')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='starnutazione',
            field=models.CharField(choices=[('SP', 'sporadica'), ('AS', 'a salve')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='turb',
            field=models.CharField(choices=[('NTR', 'normotrofici'), ('IPT', 'ipertrofici'), ('IPE', 'iperemici'), ('EMA', 'ematosi')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uso_farmaci',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
