# Generated by Django 2.2 on 2019-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190506_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='epithelium_num',
            field=models.SmallIntegerField(null=True),
        ),
    ]
