# Generated by Django 2.2 on 2019-05-06 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_slide_epithelium_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='epithelium_num',
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='anamnesis_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
