# Generated by Django 2.2 on 2019-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190506_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellextraction',
            name='epithelium_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
