# Generated by Django 2.2 on 2019-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cellextraction_epithelium_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellextraction',
            name='epithelium_num',
            field=models.SmallIntegerField(),
        ),
    ]
