# Generated by Django 2.2 on 2019-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190507_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellextraction',
            name='epithelium_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
