# Generated by Django 2.2 on 2019-05-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190507_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellextraction',
            old_name='esinophil_num',
            new_name='eosinophil_num',
        ),
    ]
