# Generated by Django 2.2 on 2019-05-08 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190508_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='pol_nas_sx',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, unique=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cell_extraction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='api.CellExtraction'),
            preserve_default=False,
        ),
    ]
