# Generated by Django 2.2 on 2019-05-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_diagnosis_cell_extraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='pol_nas_sx',
        ),
    ]
