# Generated by Django 2.2 on 2019-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_anamnesis_pol_nas_sx'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='polip_nas_sx',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, unique=True),
        ),
    ]
