# Generated by Django 2.2 on 2019-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_anamnesis_polip_nas_sx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='polip_nas_sx',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, unique=True),
        ),
    ]
