# Generated by Django 2.2 on 2019-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190508_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='essudato',
            field=models.CharField(choices=[('SI', 'sieroso'), ('MU', 'mucoso'), ('PU', 'purulento'), ('EM', 'ematico')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='ipertr_adenoidea',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='polip_nas_dx',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='prick_test',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='rinorrea',
            field=models.CharField(choices=[('SI', 'sieroso'), ('MU', 'mucoso'), ('PU', 'purulento'), ('EM', 'ematico')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
