# Generated by Django 2.2 on 2019-05-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellextraction',
            old_name='lymphocye_num',
            new_name='lymphocyte_num',
        ),
    ]
