# Generated by Django 2.2 on 2019-05-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190508_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
