# Generated by Django 2.2 on 2019-05-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
