# Generated by Django 2.2 on 2019-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='rinorrea_espans',
            field=models.CharField(choices=[('SX', 'sinistra'), ('DX', 'destra'), ('EX', 'bilaterale')], max_length=2, null=True),
        ),
    ]
