# Generated by Django 2.2 on 2019-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_anamnesis_rinorrea_espans'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='valv_nas',
            field=models.CharField(choices=[('NFN', 'normofunzionante'), ('INS', 'insufficienza sinistra'), ('IND', 'insufficienza destra'), ('INE', 'insufficienza bilaterale')], max_length=3, null=True),
        ),
    ]
