# Generated by Django 2.2 on 2019-05-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_diagnosis_diagnosisextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='prick_test',
        ),
        migrations.CreateModel(
            name='PrickTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prick_test', to='api.Allergy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='prick_test',
            field=models.ManyToManyField(to='api.PrickTest'),
        ),
    ]
