# Generated by Django 2.2 on 2019-05-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190511_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrickTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('allergy', models.ManyToManyField(to='api.Allergy')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prick_test', to='api.Anamnesis')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
