# Generated by Django 2.2 on 2019-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_pricktest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrickTest',
        ),
    ]
