# Generated by Django 2.2 on 2019-05-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
