# Generated by Django 2.2 on 2019-05-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(null=True, upload_to='report/')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.Anamnesis')),
                ('cell_extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.CellExtraction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
