# Generated by Django 2.2 on 2019-05-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anamnesis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.Anamnesis'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cell_extraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.CellExtraction'),
        ),
    ]
