# Generated by Django 2.2 on 2019-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20190529_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellextraction',
            name='other_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
