# Generated by Django 2.2 on 2019-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_cellextraction_other_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='appunti_alter_rinofaringe',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='appunti_anam_fam',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='appunti_sintom',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='conclusioni_esame',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='esame_orecchie',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
